### ISSUE TITLE
pongbot posted nsfw gifs

### ISSUE THREAD

**Issue by jethrolarson** [dblock/slack-gamebot#142] opened 2017-05-05 17:15 UTC
Maybe this needs to go to giphy but still:

http://media2.giphy.com/media/nsgQGSsX8Utd6/giphy.gif (NSFW)

**Comment by dblock** [comment] 2017-05-05 20:46
Yes you should report this to Giphy. Premium teams can disable GIFs.

**Comment by dblock** [comment] 2017-05-05 20:47
Closing this as a duplicate of https://github.com/dblock/slack-gamebot/issues/137.

**Closed by dblock** 2017-05-05 20:46 UTC
