### ISSUE TITLE
Some bot commands not working

### ISSUE THREAD

**Issue by Cr4nkY4nk3r** [dblock/slack-gamebot#102] opened 2016-04-18 20:21 UTC
@botname set gifs off returns the following message:

BOT is invalid

Set aliases command and set api command return the same message. Challenge, accept, lost, team, season, matches appear to work okay. Haven't tried other commands.

**Comment by dblock** [comment] 2016-04-19 13:33
Someone else has reported something similar and I wasn't able to get to the bottom of this. You should be able to DM the bot though without saying `@botname` and that should work for settings. Would love any help with debugging this.

**Comment by dblock** [comment] 2016-04-19 13:34
https://github.com/dblock/slack-gamebot/issues/101

**Comment by Cr4nkY4nk3r** [comment] 2016-04-19 14:00
Interesting results, but they truly show the reason I'm trying to turn gifs off.

DM's:
set gifs off
BOT is invalid (display giphy of someone throwing a monitor across a room)

pongbot: set gifs off
BOT is invalid (display giphy of cartoon character shrugging shoulders)

@pongbot: set gifs off 
BOT is invalid (displays giphy of flashing "Computer Malfunction" message

pongbot set gifs off
BOT is invalid (displays some sort of growing sculpture)

@pongbot set gifs off
BOT is invalid (displays giphy of flashing skulls)

set gifs
BOT GIFs for team TEAMNAME are off (displays giphy of some actor saying "It's time to have fun and relax")

In #pong channel:
set gifs
(no response)
@pongbot challenge @daniel 
BOT rick challenged daniel to a match (displays animated giphy of David Cameron tightening a belt around his neck with one hand, and jerking off under a podium with the other)

There's no curation of giphy results, and there's no rhyme or reason as to what will show up, or why.

If you can give me any idea of where to get more troubleshooting info for you, I'd be more than willing to give it to you!

**Comment by Cr4nkY4nk3r** [comment] 2016-04-19 14:02
Sorry - meant to give you giphy link: http://media3.giphy.com/media/ku3RKaWRAig4U/giphy.gif

**Comment by dblock** [comment] 2016-04-19 21:42
Did you try `@pongbot set gifs off` in the #pong channel?

**Comment by Cr4nkY4nk3r** [comment] 2016-04-19 21:57
Yeah, both with and without the colon.

**Comment by dblock** [comment] 2016-04-20 19:28
I'll give this some attention this week.

**Comment by Cr4nkY4nk3r** [comment] 2016-04-20 19:50
Thanks!

**Comment by dblock** [comment] 2016-04-23 12:13
I spent some time on this and I cannot reproduce this, so I don't know where it comes from and the logs aren't helpful. Still want to know your team's name @Cr4nkY4nk3r and I'll set your GIFs off manually. It will also help me to debug.

**Comment by dblock** [comment] 2016-04-23 12:32
I think I got it ... will take me a bit of time to fix, stay tuned.

**Comment by dblock** [comment] 2016-04-23 21:06
This should be now fixed, please give it a try, LMK.

**Comment by Cr4nkY4nk3r** [comment] 2016-04-25 13:06
Daniel,

Appears to work like a champ - thanks so much!

Rick

**Comment by dblock** [comment] 2016-04-25 14:39
👍  please consider sponsoring this free service, http://playplay.io/#sponsors

**Comment by dblock** [comment] 2016-05-10 19:41
Looks like this is still happening to others.

![invalid](https://cloud.githubusercontent.com/assets/542335/15160028/afd62e32-16c5-11e6-9348-c0ea95c02add.png)

**Closed** 2019-03-22 20:46 UTC
Labels: bug?
